//
// This file was generated by the JavaTM Architecture for XML Binding( JAXB ) Reference
// Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.02.10 at 05:35:25 PM BRST
//

package org.nmap;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 *
 */
@XmlAccessorType( XmlAccessType.FIELD )
@XmlType( name = "", propOrder = {"extrareasons"} )
@XmlRootElement( name = "extraports" )
public class Extraports
{

	/**
	 * Gets the value of the count property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getCount()
	{
		return this.count;
	}

	/**
	 * Gets the value of the extrareasons property.
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any
	 * modification you make to the returned list will be present inside the JAXB object. This is
	 * why there is not a <CODE>set</CODE> method for the extrareasons property.
	 * <p>
	 * For example, to add a new item, do as follows:
	 *
	 * <pre>
     *    getExtrareasons( ).add( newItem );
     * </pre>
	 * <p>
	 * Objects of the following type( s ) are allowed in the list {@link Extrareasons }
	 */
	/**
	 * <p>
	 * </p>
	 *
	 * @return
	 */
	public List<Extrareasons> getExtrareasons()
	{
		if ( this.extrareasons == null )
		{
			this.extrareasons = new ArrayList<Extrareasons>();
		}
		return this.extrareasons;
	}

	/**
	 * Gets the value of the state property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getState()
	{
		return this.state;
	}

	/**
	 * Sets the value of the count property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setCount( final String value )
	{
		this.count = value;
	}

	/**
	 * Sets the value of the state property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setState( final String value )
	{
		this.state = value;
	}

	/**
	 * <p>
	 * Field <code>count</code>
	 * </p>
	 */
	@XmlAttribute( name = "count", required = true )
	@XmlJavaTypeAdapter( NormalizedStringAdapter.class )
	private String count;

	/**
	 * <p>
	 * Field <code>extrareasons</code>
	 * </p>
	 */
	private List<Extrareasons> extrareasons;

	/**
	 * <p>
	 * Field <code>state</code>
	 * </p>
	 */
	@XmlAttribute( name = "state", required = true )
	@XmlJavaTypeAdapter( NormalizedStringAdapter.class )
	private String state;

}
