//
// This file was generated by the JavaTM Architecture for XML Binding( JAXB ) Reference
// Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.02.10 at 05:35:25 PM BRST
//

package org.nmap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * 
 */
@XmlAccessorType( XmlAccessType.FIELD )
@XmlType( name = "" )
@XmlRootElement( name = "finished" )
public class Finished
{

	/**
	 * Gets the value of the elapsed property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getElapsed( )
	{
		return this.elapsed;
	}

	/**
	 * Gets the value of the errormsg property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getErrormsg( )
	{
		return this.errormsg;
	}

	/**
	 * Gets the value of the exit property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getExit( )
	{
		return this.exit;
	}

	/**
	 * Gets the value of the summary property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getSummary( )
	{
		return this.summary;
	}

	/**
	 * Gets the value of the time property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getTime( )
	{
		return this.time;
	}

	/**
	 * Gets the value of the timestr property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getTimestr( )
	{
		return this.timestr;
	}

	/**
	 * Sets the value of the elapsed property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setElapsed( final String value )
	{
		this.elapsed = value;
	}

	/**
	 * Sets the value of the errormsg property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setErrormsg( final String value )
	{
		this.errormsg = value;
	}

	/**
	 * Sets the value of the exit property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setExit( final String value )
	{
		this.exit = value;
	}

	/**
	 * Sets the value of the summary property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setSummary( final String value )
	{
		this.summary = value;
	}

	/**
	 * Sets the value of the time property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setTime( final String value )
	{
		this.time = value;
	}

	/**
	 * Sets the value of the timestr property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setTimestr( final String value )
	{
		this.timestr = value;
	}

	@XmlAttribute( name = "elapsed", required = true )
	@XmlJavaTypeAdapter( NormalizedStringAdapter.class )
	private String elapsed;

	@XmlAttribute( name = "errormsg" )
	@XmlJavaTypeAdapter( NormalizedStringAdapter.class )
	private String errormsg;

	@XmlAttribute( name = "exit" )
	@XmlJavaTypeAdapter( CollapsedStringAdapter.class )
	private String exit;

	@XmlAttribute( name = "summary" )
	@XmlJavaTypeAdapter( NormalizedStringAdapter.class )
	private String summary;

	@XmlAttribute( name = "time", required = true )
	@XmlJavaTypeAdapter( NormalizedStringAdapter.class )
	private String time;

	@XmlAttribute( name = "timestr" )
	@XmlJavaTypeAdapter( NormalizedStringAdapter.class )
	private String timestr;

}
