//
// This file was generated by the JavaTM Architecture for XML Binding( JAXB ) Reference
// Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.02.10 at 05:35:25 PM BRST
//

package org.nmap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * 
 */
@XmlAccessorType( XmlAccessType.FIELD )
@XmlType( name = "" )
@XmlRootElement( name = "hop" )
public class Hop
{

	/**
	 * Gets the value of the host property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getHost( )
	{
		return this.host;
	}

	/**
	 * Gets the value of the ipaddr property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getIpaddr( )
	{
		return this.ipaddr;
	}

	/**
	 * Gets the value of the rtt property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getRtt( )
	{
		return this.rtt;
	}

	/**
	 * Gets the value of the ttl property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getTtl( )
	{
		return this.ttl;
	}

	/**
	 * Sets the value of the host property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setHost( final String value )
	{
		this.host = value;
	}

	/**
	 * Sets the value of the ipaddr property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setIpaddr( final String value )
	{
		this.ipaddr = value;
	}

	/**
	 * Sets the value of the rtt property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setRtt( final String value )
	{
		this.rtt = value;
	}

	/**
	 * Sets the value of the ttl property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setTtl( final String value )
	{
		this.ttl = value;
	}

	@XmlAttribute( name = "host" )
	@XmlJavaTypeAdapter( NormalizedStringAdapter.class )
	private String host;

	@XmlAttribute( name = "ipaddr" )
	@XmlJavaTypeAdapter( NormalizedStringAdapter.class )
	private String ipaddr;

	@XmlAttribute( name = "rtt" )
	@XmlJavaTypeAdapter( NormalizedStringAdapter.class )
	private String rtt;

	@XmlAttribute( name = "ttl", required = true )
	@XmlJavaTypeAdapter( NormalizedStringAdapter.class )
	private String ttl;

}
