//
// This file was generated by the JavaTM Architecture for XML Binding( JAXB ) Reference
// Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.02.10 at 05:35:25 PM BRST
//

package org.nmap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * 
 */
@XmlAccessorType( XmlAccessType.FIELD )
@XmlType( name = "" )
@XmlRootElement( name = "hosts" )
public class Hosts
{

	/**
	 * Gets the value of the down property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getDown()
	{
		if ( this.down == null )
		{
			return "0";
		}
		return this.down;
	}

	/**
	 * Gets the value of the total property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getTotal()
	{
		return this.total;
	}

	/**
	 * Gets the value of the up property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getUp()
	{
		if ( this.up == null )
		{
			return "0";
		}
		return this.up;
	}

	/**
	 * Sets the value of the down property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setDown( final String value )
	{
		this.down = value;
	}

	/**
	 * Sets the value of the total property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setTotal( final String value )
	{
		this.total = value;
	}

	/**
	 * Sets the value of the up property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setUp( final String value )
	{
		this.up = value;
	}

	@XmlAttribute( name = "down" )
	@XmlJavaTypeAdapter( NormalizedStringAdapter.class )
	private String down;

	@XmlAttribute( name = "total", required = true )
	@XmlJavaTypeAdapter( NormalizedStringAdapter.class )
	private String total;

	@XmlAttribute( name = "up" )
	@XmlJavaTypeAdapter( NormalizedStringAdapter.class )
	private String up;

}
