//
// This file was generated by the JavaTM Architecture for XML Binding( JAXB ) Reference
// Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.02.10 at 05:35:25 PM BRST
//

package org.nmap;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 *
 */
@XmlAccessorType( XmlAccessType.FIELD )
@XmlType( name = "", propOrder = {"statusOrAddressOrHostnamesOrSmurfOrPortsOrOsOrDistanceOrUptimeOrTcpsequenceOrIpidsequenceOrTcptssequenceOrHostscriptOrTraceOrTimes"} )
@XmlRootElement( name = "host" )
public class Host
{

	/**
	 * Gets the value of the comment property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getComment()
	{
		return this.comment;
	}

	/**
	 * Gets the value of the endtime property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getEndtime()
	{
		return this.endtime;
	}

	/**
	 * Gets the value of the starttime property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getStarttime()
	{
		return this.starttime;
	}

	/**
	 * Gets the value of the
	 * statusOrAddressOrHostnamesOrSmurfOrPortsOrOsOrDistanceOrUptimeOrTcpsequenceOrIpidsequenceOrTcptssequenceOrHostscriptOrTraceOrTimes
	 * property.
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any
	 * modification you make to the returned list will be present inside the JAXB object. This is
	 * why there is not a <CODE>set</CODE> method for the
	 * statusOrAddressOrHostnamesOrSmurfOrPortsOrOsOrDistanceOrUptimeOrTcpsequenceOrIpidsequenceOrTcptssequenceOrHostscriptOrTraceOrTimes
	 * property.
	 * <p>
	 * For example, to add a new item, do as follows:
	 *
	 * <pre>
     *    getStatusOrAddressOrHostnamesOrSmurfOrPortsOrOsOrDistanceOrUptimeOrTcpsequenceOrIpidsequenceOrTcptssequenceOrHostscriptOrTraceOrTimes( ).add( newItem );
     * </pre>
	 * <p>
	 * Objects of the following type( s ) are allowed in the list {@link Status } {@link Address }
	 * {@link Hostnames } {@link Smurf } {@link Ports } {@link Os } {@link Distance } {@link Uptime }
	 * {@link Tcpsequence } {@link Ipidsequence } {@link Tcptssequence } {@link Hostscript }
	 * {@link Trace } {@link Times }
	 * 
	 * @return
	 */
	public List<Object> getStatusOrAddressOrHostnamesOrSmurfOrPortsOrOsOrDistanceOrUptimeOrTcpsequenceOrIpidsequenceOrTcptssequenceOrHostscriptOrTraceOrTimes()
	{
		if ( this.statusOrAddressOrHostnamesOrSmurfOrPortsOrOsOrDistanceOrUptimeOrTcpsequenceOrIpidsequenceOrTcptssequenceOrHostscriptOrTraceOrTimes == null )
		{
			this.statusOrAddressOrHostnamesOrSmurfOrPortsOrOsOrDistanceOrUptimeOrTcpsequenceOrIpidsequenceOrTcptssequenceOrHostscriptOrTraceOrTimes = new ArrayList<Object>();
		}
		return this.statusOrAddressOrHostnamesOrSmurfOrPortsOrOsOrDistanceOrUptimeOrTcpsequenceOrIpidsequenceOrTcptssequenceOrHostscriptOrTraceOrTimes;
	}

	/**
	 * Sets the value of the comment property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setComment( final String value )
	{
		this.comment = value;
	}

	/**
	 * Sets the value of the endtime property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setEndtime( final String value )
	{
		this.endtime = value;
	}

	/**
	 * Sets the value of the starttime property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setStarttime( final String value )
	{
		this.starttime = value;
	}

	/**
	 * <p>
	 * Field <code>comment</code>
	 * </p>
	 */
	@XmlAttribute( name = "comment" )
	@XmlJavaTypeAdapter( NormalizedStringAdapter.class )
	private String comment;

	/**
	 * <p>
	 * Field <code>endtime</code>
	 * </p>
	 */
	@XmlAttribute( name = "endtime" )
	@XmlJavaTypeAdapter( NormalizedStringAdapter.class )
	private String endtime;

	/**
	 * <p>
	 * Field <code>starttime</code>
	 * </p>
	 */
	@XmlAttribute( name = "starttime" )
	@XmlJavaTypeAdapter( NormalizedStringAdapter.class )
	private String starttime;

	/**
	 * <p>
	 * Field
	 * <code>statusOrAddressOrHostnamesOrSmurfOrPortsOrOsOrDistanceOrUptimeOrTcpsequenceOrIpidsequenceOrTcptssequenceOrHostscriptOrTraceOrTimes</code>
	 * </p>
	 */
	@XmlElements( {	@XmlElement( name = "status", type = Status.class ),
					@XmlElement( name = "address", type = Address.class ),
					@XmlElement( name = "hostnames", type = Hostnames.class ),
					@XmlElement( name = "smurf", type = Smurf.class ),
					@XmlElement( name = "ports", type = Ports.class ),
					@XmlElement( name = "os", type = Os.class ),
					@XmlElement( name = "distance", type = Distance.class ),
					@XmlElement( name = "uptime", type = Uptime.class ),
					@XmlElement( name = "tcpsequence", type = Tcpsequence.class ),
					@XmlElement( name = "ipidsequence", type = Ipidsequence.class ),
					@XmlElement( name = "tcptssequence", type = Tcptssequence.class ),
					@XmlElement( name = "hostscript", type = Hostscript.class ),
					@XmlElement( name = "trace", type = Trace.class ),
					@XmlElement( name = "times", type = Times.class )} )
	private List<Object> statusOrAddressOrHostnamesOrSmurfOrPortsOrOsOrDistanceOrUptimeOrTcpsequenceOrIpidsequenceOrTcptssequenceOrHostscriptOrTraceOrTimes;

}
