//
// This file was generated by the JavaTM Architecture for XML Binding( JAXB ) Reference
// Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.02.10 at 05:35:25 PM BRST
//

package org.nmap;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 *
 */
/**
 * <p>
 * </p>
 * 
 * @author oliver.kuster
 * @version 1.0 Created on 09/04/2015
 */
@XmlAccessorType( XmlAccessType.FIELD )
@XmlType( name = "", propOrder = {"hostname"} )
@XmlRootElement( name = "hostnames" )
public class Hostnames
{

	/**
	 * Gets the value of the hostname property.
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any
	 * modification you make to the returned list will be present inside the JAXB object. This is
	 * why there is not a <CODE>set</CODE> method for the hostname property.
	 * <p>
	 * For example, to add a new item, do as follows:
	 *
	 * <pre>
     *    getHostname( ).add( newItem );
     * </pre>
	 * <p>
	 * Objects of the following type( s ) are allowed in the list {@link Hostname }
	 * 
	 * @return
	 */
	public List<Hostname> getHostname()
	{
		if ( this.hostname == null )
		{
			this.hostname = new ArrayList<Hostname>();
		}
		return this.hostname;
	}

	/**
	 * <p>
	 * Field <code>hostname</code>
	 * </p>
	 */
	private List<Hostname> hostname;

}
