//
// This file was generated by the JavaTM Architecture for XML Binding( JAXB ) Reference
// Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.02.10 at 05:35:25 PM BRST
//

package org.nmap;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java element interface
 * generated in the org.nmap package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation
 * for XML content. The Java representation of XML content can consist of schema derived interfaces
 * and classes representing the binding of schema type definitions, element declarations and model
 * groups. Factory methods for each of these are provided in this class.
 * 
 * @return
 */
@XmlRegistry
public class ObjectFactory
{

	/**
	 * Create a new ObjectFactory that can be used to create new instances of schema derived classes
	 * for package: org.nmap
	 * 
	 * @return
	 */
	public ObjectFactory()
	{
	}

	/**
	 * Create an instance of {@link Address }
	 * 
	 * @return
	 */
	public Address createAddress()
	{
		return new Address();
	}

	/**
	 * Create an instance of {@link Cpe }
	 * 
	 * @return
	 */
	public Cpe createCpe()
	{
		return new Cpe();
	}

	/**
	 * Create an instance of {@link Debugging }
	 * 
	 * @return
	 */
	public Debugging createDebugging()
	{
		return new Debugging();
	}

	/**
	 * Create an instance of {@link Distance }
	 * 
	 * @return
	 */
	public Distance createDistance()
	{
		return new Distance();
	}

	/**
	 * Create an instance of {@link Elem }
	 * 
	 * @return
	 */
	public Elem createElem()
	{
		return new Elem();
	}

	/**
	 * Create an instance of {@link Extraports }
	 * 
	 * @return
	 */
	public Extraports createExtraports()
	{
		return new Extraports();
	}

	/**
	 * Create an instance of {@link Extrareasons }
	 * 
	 * @return
	 */
	public Extrareasons createExtrareasons()
	{
		return new Extrareasons();
	}

	/**
	 * Create an instance of {@link Finished }
	 * 
	 * @return
	 */
	public Finished createFinished()
	{
		return new Finished();
	}

	/**
	 * Create an instance of {@link Hop }
	 * 
	 * @return
	 */
	public Hop createHop()
	{
		return new Hop();
	}

	/**
	 * Create an instance of {@link Host }
	 * 
	 * @return
	 */
	public Host createHost()
	{
		return new Host();
	}

	/**
	 * Create an instance of {@link Hostname }
	 * 
	 * @return
	 */
	public Hostname createHostname()
	{
		return new Hostname();
	}

	/**
	 * Create an instance of {@link Hostnames }
	 * 
	 * @return
	 */
	public Hostnames createHostnames()
	{
		return new Hostnames();
	}

	/**
	 * Create an instance of {@link Hosts }
	 * 
	 * @return
	 */
	public Hosts createHosts()
	{
		return new Hosts();
	}

	/**
	 * Create an instance of {@link Hostscript }
	 * 
	 * @return
	 */
	public Hostscript createHostscript()
	{
		return new Hostscript();
	}

	/**
	 * Create an instance of {@link Ipidsequence }
	 * 
	 * @return
	 */
	public Ipidsequence createIpidsequence()
	{
		return new Ipidsequence();
	}

	/**
	 * Create an instance of {@link Nmaprun }
	 * 
	 * @return
	 */
	public Nmaprun createNmaprun()
	{
		return new Nmaprun();
	}

	/**
	 * Create an instance of {@link Os }
	 * 
	 * @return
	 */
	public Os createOs()
	{
		return new Os();
	}

	/**
	 * Create an instance of {@link Osclass }
	 * 
	 * @return
	 */
	public Osclass createOsclass()
	{
		return new Osclass();
	}

	/**
	 * Create an instance of {@link Osfingerprint }
	 * 
	 * @return
	 */
	public Osfingerprint createOsfingerprint()
	{
		return new Osfingerprint();
	}

	/**
	 * Create an instance of {@link Osmatch }
	 * 
	 * @return
	 */
	public Osmatch createOsmatch()
	{
		return new Osmatch();
	}

	/**
	 * Create an instance of {@link Output }
	 * 
	 * @return
	 */
	public Output createOutput()
	{
		return new Output();
	}

	/**
	 * Create an instance of {@link Owner }
	 * 
	 * @return
	 */
	public Owner createOwner()
	{
		return new Owner();
	}

	/**
	 * Create an instance of {@link Port }
	 * 
	 * @return
	 */
	public Port createPort()
	{
		return new Port();
	}

	/**
	 * Create an instance of {@link Ports }
	 * 
	 * @return
	 */
	public Ports createPorts()
	{
		return new Ports();
	}

	/**
	 * Create an instance of {@link Portused }
	 * 
	 * @return
	 */
	public Portused createPortused()
	{
		return new Portused();
	}

	/**
	 * Create an instance of {@link Postscript }
	 * 
	 * @return
	 */
	public Postscript createPostscript()
	{
		return new Postscript();
	}

	/**
	 * Create an instance of {@link Prescript }
	 * 
	 * @return
	 */
	public Prescript createPrescript()
	{
		return new Prescript();
	}

	/**
	 * Create an instance of {@link Runstats }
	 * 
	 * @return
	 */
	public Runstats createRunstats()
	{
		return new Runstats();
	}

	/**
	 * Create an instance of {@link Scaninfo }
	 * 
	 * @return
	 */
	public Scaninfo createScaninfo()
	{
		return new Scaninfo();
	}

	/**
	 * Create an instance of {@link Script }
	 * 
	 * @return
	 */
	public Script createScript()
	{
		return new Script();
	}

	/**
	 * Create an instance of {@link Service }
	 * 
	 * @return
	 */
	public Service createService()
	{
		return new Service();
	}

	/**
	 * Create an instance of {@link Smurf }
	 * 
	 * @return
	 */
	public Smurf createSmurf()
	{
		return new Smurf();
	}

	/**
	 * Create an instance of {@link State }
	 * 
	 * @return
	 */
	public State createState()
	{
		return new State();
	}

	/**
	 * Create an instance of {@link Status }
	 * 
	 * @return
	 */
	public Status createStatus()
	{
		return new Status();
	}

	/**
	 * Create an instance of {@link Table }
	 * 
	 * @return
	 */
	public Table createTable()
	{
		return new Table();
	}

	/**
	 * Create an instance of {@link Target }
	 * 
	 * @return
	 */
	public Target createTarget()
	{
		return new Target();
	}

	/**
	 * Create an instance of {@link Taskbegin }
	 * 
	 * @return
	 */
	public Taskbegin createTaskbegin()
	{
		return new Taskbegin();
	}

	/**
	 * Create an instance of {@link Taskend }
	 * 
	 * @return
	 */
	public Taskend createTaskend()
	{
		return new Taskend();
	}

	/**
	 * Create an instance of {@link Taskprogress }
	 * 
	 * @return
	 */
	public Taskprogress createTaskprogress()
	{
		return new Taskprogress();
	}

	/**
	 * Create an instance of {@link Tcpsequence }
	 * 
	 * @return
	 */
	public Tcpsequence createTcpsequence()
	{
		return new Tcpsequence();
	}

	/**
	 * Create an instance of {@link Tcptssequence }
	 * 
	 * @return
	 */
	public Tcptssequence createTcptssequence()
	{
		return new Tcptssequence();
	}

	/**
	 * Create an instance of {@link Times }
	 * 
	 * @return
	 */
	public Times createTimes()
	{
		return new Times();
	}

	/**
	 * Create an instance of {@link Trace }
	 * 
	 * @return
	 */
	public Trace createTrace()
	{
		return new Trace();
	}

	/**
	 * Create an instance of {@link Uptime }
	 * 
	 * @return
	 */
	public Uptime createUptime()
	{
		return new Uptime();
	}

	/**
	 * Create an instance of {@link Verbose }
	 * 
	 * @return
	 */
	public Verbose createVerbose()
	{
		return new Verbose();
	}

}
