//
// This file was generated by the JavaTM Architecture for XML Binding( JAXB ) Reference
// Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.02.10 at 05:35:25 PM BRST
//

package org.nmap;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 *
 */
@XmlAccessorType( XmlAccessType.FIELD )
@XmlType( name = "", propOrder = {	"portused",
									"osmatch",
									"osfingerprint"} )
@XmlRootElement( name = "os" )
public class Os
{

	/**
	 * Gets the value of the osfingerprint property.
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any
	 * modification you make to the returned list will be present inside the JAXB object. This is
	 * why there is not a <CODE>set</CODE> method for the osfingerprint property.
	 * <p>
	 * For example, to add a new item, do as follows:
	 *
	 * <pre>
     *    getOsfingerprint( ).add( newItem );
     * </pre>
	 * <p>
	 * Objects of the following type( s ) are allowed in the list {@link Osfingerprint }
	 *
	 * @return
	 */
	public List<Osfingerprint> getOsfingerprint()
	{
		if ( this.osfingerprint == null )
		{
			this.osfingerprint = new ArrayList<Osfingerprint>();
		}
		return this.osfingerprint;
	}

	/**
	 * Gets the value of the osmatch property.
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any
	 * modification you make to the returned list will be present inside the JAXB object. This is
	 * why there is not a <CODE>set</CODE> method for the osmatch property.
	 * <p>
	 * For example, to add a new item, do as follows:
	 *
	 * <pre>
     *    getOsmatch( ).add( newItem );
     * </pre>
	 * <p>
	 * Objects of the following type( s ) are allowed in the list {@link Osmatch }
	 * 
	 * @return
	 */
	public List<Osmatch> getOsmatch()
	{
		if ( this.osmatch == null )
		{
			this.osmatch = new ArrayList<Osmatch>();
		}
		return this.osmatch;
	}

	/**
	 * Gets the value of the portused property.
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any
	 * modification you make to the returned list will be present inside the JAXB object. This is
	 * why there is not a <CODE>set</CODE> method for the portused property.
	 * <p>
	 * For example, to add a new item, do as follows:
	 *
	 * <pre>
     *    getPortused( ).add( newItem );
     * </pre>
	 * <p>
	 * Objects of the following type( s ) are allowed in the list {@link Portused }
	 * 
	 * @return
	 */
	public List<Portused> getPortused()
	{
		if ( this.portused == null )
		{
			this.portused = new ArrayList<Portused>();
		}
		return this.portused;
	}

	/**
	 * <p>
	 * Field <code>osfingerprint</code>
	 * </p>
	 */
	private List<Osfingerprint> osfingerprint;

	/**
	 * <p>
	 * Field <code>osmatch</code>
	 * </p>
	 */
	private List<Osmatch> osmatch;

	/**
	 * <p>
	 * Field <code>portused</code>
	 * </p>
	 */
	private List<Portused> portused;

}
