//
// This file was generated by the JavaTM Architecture for XML Binding( JAXB ) Reference
// Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.02.10 at 05:35:25 PM BRST
//

package org.nmap;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 *
 */
@XmlAccessorType( XmlAccessType.FIELD )
@XmlType( name = "", propOrder = {"cpe"} )
@XmlRootElement( name = "osclass" )
public class Osclass
{

	/**
	 * Gets the value of the accuracy property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getAccuracy()
	{
		return this.accuracy;
	}

	/**
	 * Gets the value of the cpe property.
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any
	 * modification you make to the returned list will be present inside the JAXB object. This is
	 * why there is not a <CODE>set</CODE> method for the cpe property.
	 * <p>
	 * For example, to add a new item, do as follows:
	 *
	 * <pre>
     *    getCpe( ).add( newItem );
     * </pre>
	 * <p>
	 * Objects of the following type( s ) are allowed in the list {@link Cpe }
	 * 
	 * @return
	 */
	public List<Cpe> getCpe()
	{
		if ( this.cpe == null )
		{
			this.cpe = new ArrayList<Cpe>();
		}
		return this.cpe;
	}

	/**
	 * Gets the value of the osfamily property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getOsfamily()
	{
		return this.osfamily;
	}

	/**
	 * Gets the value of the osgen property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getOsgen()
	{
		return this.osgen;
	}

	/**
	 * Gets the value of the type property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getType()
	{
		return this.type;
	}

	/**
	 * Gets the value of the vendor property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getVendor()
	{
		return this.vendor;
	}

	/**
	 * Sets the value of the accuracy property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setAccuracy( final String value )
	{
		this.accuracy = value;
	}

	/**
	 * Sets the value of the osfamily property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setOsfamily( final String value )
	{
		this.osfamily = value;
	}

	/**
	 * Sets the value of the osgen property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setOsgen( final String value )
	{
		this.osgen = value;
	}

	/**
	 * Sets the value of the type property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setType( final String value )
	{
		this.type = value;
	}

	/**
	 * Sets the value of the vendor property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setVendor( final String value )
	{
		this.vendor = value;
	}

	@XmlAttribute( name = "accuracy", required = true )
	@XmlJavaTypeAdapter( NormalizedStringAdapter.class )
	private String accuracy;

	private List<Cpe> cpe;

	@XmlAttribute( name = "osfamily", required = true )
	@XmlJavaTypeAdapter( NormalizedStringAdapter.class )
	private String osfamily;

	@XmlAttribute( name = "osgen" )
	@XmlJavaTypeAdapter( NormalizedStringAdapter.class )
	private String osgen;

	@XmlAttribute( name = "type" )
	@XmlJavaTypeAdapter( NormalizedStringAdapter.class )
	private String type;

	@XmlAttribute( name = "vendor", required = true )
	@XmlJavaTypeAdapter( NormalizedStringAdapter.class )
	private String vendor;

}
