//
// This file was generated by the JavaTM Architecture for XML Binding( JAXB ) Reference
// Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.02.10 at 05:35:25 PM BRST
//

package org.nmap;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 *
 */
@XmlAccessorType( XmlAccessType.FIELD )
@XmlType( name = "", propOrder = {	"extraports",
									"port"} )
@XmlRootElement( name = "ports" )
public class Ports
{

	/**
	 * Gets the value of the extraports property.
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any
	 * modification you make to the returned list will be present inside the JAXB object. This is
	 * why there is not a <CODE>set</CODE> method for the extraports property.
	 * <p>
	 * For example, to add a new item, do as follows:
	 *
	 * <pre>
     *    getExtraports( ).add( newItem );
     * </pre>
	 * <p>
	 * Objects of the following type( s ) are allowed in the list {@link Extraports }
	 *
	 * @return
	 */
	public List<Extraports> getExtraports()
	{
		if ( this.extraports == null )
		{
			this.extraports = new ArrayList<Extraports>();
		}
		return this.extraports;
	}

	/**
	 * Gets the value of the port property.
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any
	 * modification you make to the returned list will be present inside the JAXB object. This is
	 * why there is not a <CODE>set</CODE> method for the port property.
	 * <p>
	 * For example, to add a new item, do as follows:
	 *
	 * <pre>
     *    getPort( ).add( newItem );
     * </pre>
	 * <p>
	 * Objects of the following type( s ) are allowed in the list {@link Port }
	 *
	 * @return
	 */
	public List<Port> getPort()
	{
		if ( this.port == null )
		{
			this.port = new ArrayList<Port>();
		}
		return this.port;
	}

	/**
	 * <p>
	 * Field <code>extraports</code>
	 * </p>
	 */
	private List<Extraports> extraports;

	/**
	 * <p>
	 * Field <code>port</code>
	 * </p>
	 */
	private List<Port> port;

}
