//
// This file was generated by the JavaTM Architecture for XML Binding( JAXB ) Reference
// Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.02.10 at 05:35:25 PM BRST
//

package org.nmap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 
 */
@XmlAccessorType( XmlAccessType.FIELD )
@XmlType( name = "", propOrder = {	"finished",
									"hosts"} )
@XmlRootElement( name = "runstats" )
public class Runstats
{

	/**
	 * Gets the value of the finished property.
	 * 
	 * @return possible object is {@link Finished }
	 */
	public Finished getFinished( )
	{
		return this.finished;
	}

	/**
	 * Gets the value of the hosts property.
	 * 
	 * @return possible object is {@link Hosts }
	 */
	public Hosts getHosts( )
	{
		return this.hosts;
	}

	/**
	 * Sets the value of the finished property.
	 * 
	 * @param value
	 *            allowed object is {@link Finished }
	 */
	public void setFinished( final Finished value )
	{
		this.finished = value;
	}

	/**
	 * Sets the value of the hosts property.
	 * 
	 * @param value
	 *            allowed object is {@link Hosts }
	 */
	public void setHosts( final Hosts value )
	{
		this.hosts = value;
	}

	@XmlElement( required = true )
	private Finished finished;

	@XmlElement( required = true )
	private Hosts hosts;

}
