//
// This file was generated by the JavaTM Architecture for XML Binding( JAXB ) Reference
// Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.02.10 at 05:35:25 PM BRST
//

package org.nmap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * 
 */
@XmlAccessorType( XmlAccessType.FIELD )
@XmlType( name = "" )
@XmlRootElement( name = "scaninfo" )
public class Scaninfo
{

	/**
	 * Gets the value of the numservices property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getNumservices( )
	{
		return this.numservices;
	}

	/**
	 * Gets the value of the protocol property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getProtocol( )
	{
		return this.protocol;
	}

	/**
	 * Gets the value of the scanflags property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getScanflags( )
	{
		return this.scanflags;
	}

	/**
	 * Gets the value of the services property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getServices( )
	{
		return this.services;
	}

	/**
	 * Gets the value of the type property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getType( )
	{
		return this.type;
	}

	/**
	 * Sets the value of the numservices property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setNumservices( final String value )
	{
		this.numservices = value;
	}

	/**
	 * Sets the value of the protocol property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setProtocol( final String value )
	{
		this.protocol = value;
	}

	/**
	 * Sets the value of the scanflags property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setScanflags( final String value )
	{
		this.scanflags = value;
	}

	/**
	 * Sets the value of the services property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setServices( final String value )
	{
		this.services = value;
	}

	/**
	 * Sets the value of the type property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setType( final String value )
	{
		this.type = value;
	}

	@XmlAttribute( name = "numservices", required = true )
	@XmlJavaTypeAdapter( NormalizedStringAdapter.class )
	private String numservices;

	@XmlAttribute( name = "protocol", required = true )
	@XmlJavaTypeAdapter( CollapsedStringAdapter.class )
	private String protocol;

	@XmlAttribute( name = "scanflags" )
	@XmlJavaTypeAdapter( NormalizedStringAdapter.class )
	private String scanflags;

	@XmlAttribute( name = "services", required = true )
	@XmlJavaTypeAdapter( NormalizedStringAdapter.class )
	private String services;

	@XmlAttribute( name = "type", required = true )
	@XmlJavaTypeAdapter( CollapsedStringAdapter.class )
	private String type;

}
