//
// This file was generated by the JavaTM Architecture for XML Binding( JAXB ) Reference
// Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.02.10 at 05:35:25 PM BRST
//

package org.nmap;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 *
 */
@XmlAccessorType( XmlAccessType.FIELD )
@XmlType( name = "", propOrder = {"tableOrElem"} )
@XmlRootElement( name = "script" )
public class Script
{

	/**
	 * Gets the value of the id property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getId()
	{
		return this.id;
	}

	/**
	 * Gets the value of the output property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getOutput()
	{
		return this.output;
	}

	/**
	 * Gets the value of the tableOrElem property.
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any
	 * modification you make to the returned list will be present inside the JAXB object. This is
	 * why there is not a <CODE>set</CODE> method for the tableOrElem property.
	 * <p>
	 * For example, to add a new item, do as follows:
	 *
	 * <pre>
     *    getTableOrElem( ).add( newItem );
     * </pre>
	 * <p>
	 * Objects of the following type( s ) are allowed in the list {@link Table } {@link Elem }
	 * 
	 * @return
	 */
	public List<Object> getTableOrElem()
	{
		if ( this.tableOrElem == null )
		{
			this.tableOrElem = new ArrayList<Object>();
		}
		return this.tableOrElem;
	}

	/**
	 * Sets the value of the id property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setId( final String value )
	{
		this.id = value;
	}

	/**
	 * Sets the value of the output property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setOutput( final String value )
	{
		this.output = value;
	}

	@XmlAttribute( name = "id", required = true )
	@XmlJavaTypeAdapter( NormalizedStringAdapter.class )
	private String id;

	@XmlAttribute( name = "output", required = true )
	@XmlJavaTypeAdapter( NormalizedStringAdapter.class )
	private String output;

	@XmlElements( {	@XmlElement( name = "table", type = Table.class ),
					@XmlElement( name = "elem", type = Elem.class )} )
	private List<Object> tableOrElem;

}
