//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.02.10 at 05:35:25 PM BRST
//

package org.nmap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 *
 */
@XmlAccessorType( XmlAccessType.FIELD )
@XmlType( name = "" )
@XmlRootElement( name = "target" )
public class Target
{

	/**
	 * <p>
	 * </p>
	 */
	public Target()
	{
		super();
	}

	/**
	 * Gets the value of the reason property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getReason()
	{
		return this.reason;
	}

	/**
	 * Gets the value of the specification property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getSpecification()
	{
		return this.specification;
	}

	/**
	 * Gets the value of the status property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getStatus()
	{
		return this.status;
	}

	/**
	 * Sets the value of the reason property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setReason( final String value )
	{
		this.reason = value;
	}

	/**
	 * Sets the value of the specification property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setSpecification( final String value )
	{
		this.specification = value;
	}

	/**
	 * Sets the value of the status property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setStatus( final String value )
	{
		this.status = value;
	}

	/**
	 * <p>
	 * Field <code>reason</code>
	 * </p>
	 */
	@XmlAttribute( name = "reason" )
	@XmlJavaTypeAdapter( CollapsedStringAdapter.class )
	protected String reason;

	/**
	 * <p>
	 * Field <code>specification</code>
	 * </p>
	 */
	@XmlAttribute( name = "specification", required = true )
	@XmlJavaTypeAdapter( NormalizedStringAdapter.class )
	protected String specification;

	/**
	 * <p>
	 * Field <code>status</code>
	 * </p>
	 */
	@XmlAttribute( name = "status" )
	@XmlJavaTypeAdapter( CollapsedStringAdapter.class )
	protected String status;

}
