//
// This file was generated by the JavaTM Architecture for XML Binding( JAXB ) Reference
// Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.02.10 at 05:35:25 PM BRST
//

package org.nmap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 *
 */
@XmlAccessorType( XmlAccessType.FIELD )
@XmlType( name = "" )
@XmlRootElement( name = "times" )
public class Times
{

	/**
	 * <p>
	 * </p>
	 */
	public Times()
	{
		super();
	}

	/**
	 * Gets the value of the rttvar property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getRttvar()
	{
		return this.rttvar;
	}

	/**
	 * Gets the value of the srtt property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getSrtt()
	{
		return this.srtt;
	}

	/**
	 * Gets the value of the to property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getTo()
	{
		return this.to;
	}

	/**
	 * Sets the value of the rttvar property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setRttvar( final String value )
	{
		this.rttvar = value;
	}

	/**
	 * Sets the value of the srtt property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setSrtt( final String value )
	{
		this.srtt = value;
	}

	/**
	 * Sets the value of the to property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setTo( final String value )
	{
		this.to = value;
	}

	/**
	 * <p>
	 * Field <code>rttvar</code>
	 * </p>
	 */
	@XmlAttribute( name = "rttvar", required = true )
	@XmlJavaTypeAdapter( NormalizedStringAdapter.class )
	private String rttvar;

	/**
	 * <p>
	 * Field <code>srtt</code>
	 * </p>
	 */
	@XmlAttribute( name = "srtt", required = true )
	@XmlJavaTypeAdapter( NormalizedStringAdapter.class )
	private String srtt;

	/**
	 * <p>
	 * Field <code>to</code>
	 * </p>
	 */
	@XmlAttribute( name = "to", required = true )
	@XmlJavaTypeAdapter( NormalizedStringAdapter.class )
	private String to;

}
